package com.cretas.aims.entity.notify;

import com.cretas.aims.entity.BaseEntity;
import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.Where;

import java.util.*;

/**
 * 通知模板 — Phase 3 Canvas-Notify Step T2.
 *
 * <p>Factory-scoped, (factoryId, templateCode) UNIQUE. body_template 支持 {{var}} 占位符,
 * 由 {@link com.cretas.aims.service.notify.TemplateEngine#render} 在 send 时替换为
 * NotifyRequest.params 中对应 key 的实际值. variables_schema_json 描述模板期望的变量
 * 类型, 用于 UI auto-detect + sister 实施时的 strict-type validation.
 *
 * <p>channels 字段是 List&lt;NotifyChannel&gt; 序列化为 JSONB array, 例:
 * <pre>["WECHAT", "EMAIL"]</pre>
 *
 * <p>Maps to table {@code notify_templates} (V20260621_01).
 *
 * @since 2026-05-18 (Phase 3 skeleton)
 */
@Entity
@Table(name = "notify_templates",
       uniqueConstraints = {
           @UniqueConstraint(name = "uq_notify_templates_factory_code",
                             columnNames = {"factory_id", "template_code"})
       },
       indexes = {
           @Index(name = "idx_notify_templates_factory",
                  columnList = "factory_id")
       })
@Where(clause = "deleted_at IS NULL")
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class NotifyTemplate extends BaseEntity {

    /** UUID primary key, generated by DB ({@code DEFAULT gen_random_uuid()}). */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "factory_id", length = 50, nullable = false)
    private String factoryId;

    /** 业务 key, 如 {@code PO_APPROVAL_PENDING}. */
    @Column(name = "template_code", length = 100, nullable = false)
    private String templateCode;

    /** 通知标题, 也可含 {{var}} 占位符. */
    @Column(name = "title", length = 255)
    private String title;

    /** 正文模板, 支持 {{var}} 占位符. TEXT 不限长度. */
    @Column(name = "body_template", columnDefinition = "TEXT")
    private String bodyTemplate;

    /**
     * 启用的渠道列表. JSONB array of {@link NotifyChannel} 名字.
     *
     * <p>例: {@code ["WECHAT", "EMAIL"]} — 同一通知发到企业微信和邮件.
     */
    @Type(JsonBinaryType.class)
    @Column(name = "channels", columnDefinition = "jsonb")
    @Builder.Default
    private List<NotifyChannel> channels = new ArrayList<>();

    /**
     * 变量 schema. JSONB object 描述每个 {{var}} 的期望类型.
     *
     * <p>例: {@code {"amount": "number", "approverName": "string", "items": "array"}}
     */
    @Type(JsonBinaryType.class)
    @Column(name = "variables_schema_json", columnDefinition = "jsonb")
    @Builder.Default
    private Map<String, Object> variablesSchemaJson = new HashMap<>();

    /**
     * AUD-4 P1 (edge audit 2026-05-20): JPA optimistic locking version.
     *
     * <p>Hibernate manages this column automatically — first save inserts
     * with {@code version=0}, every subsequent {@code save()} or
     * {@code merge()} increments it. If two parallel PUT requests load
     * the same row (both see {@code version=N}), Hibernate's flush detects
     * the stale snapshot on the loser and throws
     * {@link org.springframework.orm.ObjectOptimisticLockingFailureException}.
     * {@link com.cretas.aims.exception.GlobalExceptionHandler} catches it
     * and surfaces a 409 with the actionHint
     * "请刷新页面查看最新数据后再编辑" — the user can retry without
     * silently losing the other user's edits (Lost Update prevention).
     *
     * <p>Column is added via Flyway {@code V20260626_02} with
     * {@code DEFAULT 0 NOT NULL}; backfill is implicit because the migration
     * runs before any code reads/writes the column.
     *
     * <p><b>Note</b>: NotifyTemplate CRUD endpoints currently return 501
     * stubs in {@link com.cretas.aims.controller.NotifyTemplateController}
     * (see QA finding B-N1). The @Version column is added now so that when
     * Phase 3 sister chat replaces the stubs with real persistence, Lost
     * Update prevention works out of the box without an entity-schema migration.
     */
    @Version
    @Column(name = "version", nullable = false)
    private Long version;
}
