-- production_reports bootstrap + material-quantity guard.
--
-- Background: production_reports has historically been created by Hibernate
-- ddl-auto on dev/test/pg profiles. Prod (ddl-auto=none) relies on Flyway and
-- no earlier migration creates this table, so the yield material-quantity
-- columns (warehouse_out_quantity / feed_in_quantity / carryover_quantity)
-- were never guaranteed on a clean Flyway-only database.
--
-- This migration is idempotent and safe on every environment:
--   * CREATE TABLE IF NOT EXISTS -> no-op where the table already exists
--     (existing dev/test/prod); bootstraps a brand-new Flyway-only DB so it
--     matches the current com.cretas.aims.entity.ProductionReport snapshot.
--   * ADD COLUMN IF NOT EXISTS  -> backfills the three material columns on an
--     existing table created before they were added (the real prod risk).
-- Column types mirror ProductionReport. On an existing table CREATE TABLE is
-- skipped entirely, so this never alters historical column definitions.

CREATE TABLE IF NOT EXISTS production_reports (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                 BIGINT,
    factory_id              VARCHAR(50)  NOT NULL,
    batch_id                BIGINT,
    worker_id               BIGINT       NOT NULL,
    report_type             VARCHAR(30)  NOT NULL,
    report_mode             VARCHAR(16)  NOT NULL,
    schema_id               VARCHAR(36),
    report_date             DATE         NOT NULL,
    reporter_name           VARCHAR(100),
    process_category        VARCHAR(200),
    product_name            VARCHAR(200),
    output_quantity         NUMERIC(12,2),
    good_quantity           NUMERIC(12,2),
    defect_quantity         NUMERIC(12,2),
    total_work_minutes      INTEGER,
    total_workers           INTEGER,
    labor_cost              NUMERIC(14,2),
    material_cost           NUMERIC(14,2),
    operation_volume        NUMERIC(10,2),
    hour_entries            JSONB,
    non_production_entries  JSONB,
    production_start_time   TIME,
    production_end_time     TIME,
    custom_fields           JSONB,
    photos                  JSONB,
    status                  VARCHAR(20),
    rejection_reason        VARCHAR(500),
    synced_to_smartbi       BOOLEAN,
    process_task_id         VARCHAR(50),
    is_supplemental         BOOLEAN,
    approval_status         VARCHAR(20),
    approved_by             BIGINT,
    approved_at             TIMESTAMP,
    rejected_reason         VARCHAR(500),
    notes                   VARCHAR(500),
    work_process_task_id    BIGINT,
    process_order           INTEGER,
    product_type_id         VARCHAR(100),
    input_quantity          NUMERIC(12,2),
    input_unit              VARCHAR(16),
    output_unit             VARCHAR(16),
    carryover_quantity      NUMERIC(12,2),
    source_batch_refs       JSONB,
    material_batch_refs     JSONB,
    labor_segments          JSONB,
    byproducts              JSONB,
    waste_quantity          NUMERIC(14,3),
    sample_retain_quantity  INTEGER,
    warehouse_out_quantity  NUMERIC(12,2),
    feed_in_quantity        NUMERIC(12,2),
    intermediate_batch_no   VARCHAR(64),
    source_wip_no           VARCHAR(64),
    report_kind             VARCHAR(10),
    settled                 BOOLEAN,
    settled_at              TIMESTAMP,
    reversal_of_id          BIGINT,
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP,
    deleted_at              TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pr_factory_date ON production_reports (factory_id, report_date);
CREATE INDEX IF NOT EXISTS idx_pr_batch        ON production_reports (batch_id);
CREATE INDEX IF NOT EXISTS idx_pr_worker       ON production_reports (worker_id);
CREATE INDEX IF NOT EXISTS idx_pr_type         ON production_reports (report_type);

DO $$
BEGIN
    IF to_regclass('public.production_reports') IS NOT NULL THEN
        ALTER TABLE production_reports
            ADD COLUMN IF NOT EXISTS warehouse_out_quantity NUMERIC(12,2),
            ADD COLUMN IF NOT EXISTS feed_in_quantity       NUMERIC(12,2),
            ADD COLUMN IF NOT EXISTS carryover_quantity     NUMERIC(12,2);

        COMMENT ON COLUMN production_reports.warehouse_out_quantity
            IS 'Material issued from warehouse for audit/reconciliation; not the yield denominator by itself';
        COMMENT ON COLUMN production_reports.feed_in_quantity
            IS 'Actual feed-in/input quantity; preferred yield denominator';
        COMMENT ON COLUMN production_reports.carryover_quantity
            IS 'Unconsumed remainder/carryover for this batch or step';
    END IF;
END $$;
