package com.cretas.aims.entity.bom;

import com.cretas.aims.entity.BaseEntity;
import com.cretas.aims.security.PriceSensitive;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.Where;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * M-BOM-1 BOM 配方头 (主表).
 *
 * <p>系统唯一 BOM 头表；所有生产链读取均与 {@link BomRecipeItem} 配套。
 *
 * <p>核心字段:
 * <ul>
 *   <li>{@code id} — VARCHAR(191) UUID, by {@link #assignUUID()} on persist</li>
 *   <li>{@code recipeCode} — {@code BOM-YYYYMMDD-NNN} 自动生成 (Service 层)</li>
 *   <li>{@code version} + {@code isCurrent} — 同产品多版本支持, partial unique index 保证</li>
 *   <li>{@code overallYieldRate} — 整产品级出成率 (vs item-level)</li>
 *   <li>{@code outputQuantityPerUnit} — 单份成品克数/件数 (客户: "成品 200g")</li>
 *   <li>5 个 @PriceSensitive 成本字段 (RBAC strip by PriceFieldResponseAdvice)</li>
 *   <li>{@code status} — DRAFT/ACTIVE/ARCHIVED 状态机</li>
 *   <li>{@code sourceType} — MANUAL/SAMPLE_AUTOGEN/AI_GENERATED/IMPORTED</li>
 * </ul>
 *
 * <p>关联: 1:N {@link BomRecipeItem} (LAZY + orphanRemoval).
 *
 * @author Cretas Team / Track D1
 * @since 2026-05-14
 */
@Entity
@Table(name = "bom_recipes", indexes = {
    @Index(name = "idx_br_factory_product", columnList = "factory_id, product_type_id"),
    @Index(name = "idx_br_status",          columnList = "factory_id, status")
})
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Where(clause = "deleted_at IS NULL")
public class BomRecipe extends BaseEntity {

    @Id
    @Column(name = "id", nullable = false, length = 191)
    private String id;

    @PrePersist
    void assignUUID() {
        if (id == null) {
            id = UUID.randomUUID().toString();
        }
    }

    @Column(name = "factory_id", nullable = false, length = 50)
    private String factoryId;

    /** {@code BOM-YYYYMMDD-NNN}, generated by service on create. */
    @Column(name = "recipe_code", nullable = false, length = 50)
    private String recipeCode;

    @Column(name = "product_type_id", nullable = false, length = 50)
    private String productTypeId;

    @Column(name = "product_name", nullable = false, length = 200)
    private String productName;

    @Column(name = "version", nullable = false)
    @Builder.Default
    private Integer version = 1;

    @Column(name = "is_current", nullable = false)
    @Builder.Default
    private Boolean isCurrent = false;

    /** 系统根据正式批次历史自动学习的整产品级出成率；无足够样本时为 null。 */
    @Column(name = "overall_yield_rate", precision = 6, scale = 2)
    private BigDecimal overallYieldRate;

    /** 单份成品克数/件数 (200g/份, 1个/份). */
    @Column(name = "output_quantity_per_unit", nullable = false, precision = 15, scale = 4)
    private BigDecimal outputQuantityPerUnit;

    @Column(name = "output_unit", nullable = false, length = 20)
    @Builder.Default
    private String outputUnit = "g";

    /** 该 BOM 版本固定的 SKU 净含量；不得与每单位产出数量混用。 */
    @Column(name = "net_content_quantity", precision = 15, scale = 6)
    private BigDecimal netContentQuantity;

    @Column(name = "net_content_unit", length = 20)
    private String netContentUnit;

    /** Sum of bom_recipe_items.itemCost. @PriceSensitive: stripped for non-procurement-price roles. */
    @PriceSensitive
    @Column(name = "total_material_cost", precision = 15, scale = 4)
    private BigDecimal totalMaterialCost;

    @PriceSensitive
    @Column(name = "total_labor_cost", precision = 15, scale = 4)
    private BigDecimal totalLaborCost;

    @PriceSensitive
    @Column(name = "total_overhead_cost", precision = 15, scale = 4)
    private BigDecimal totalOverheadCost;

    @PriceSensitive
    @Column(name = "total_cost", precision = 15, scale = 4)
    private BigDecimal totalCost;

    @PriceSensitive
    @Column(name = "standard_sale_price", precision = 15, scale = 2)
    private BigDecimal standardSalePrice;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 32)
    @Builder.Default
    private Status status = Status.DRAFT;

    @Column(name = "activated_at")
    private LocalDateTime activatedAt;

    @Column(name = "activated_by")
    private Long activatedBy;

    @Enumerated(EnumType.STRING)
    @Column(name = "source_type", nullable = false, length = 20)
    @Builder.Default
    private SourceType sourceType = SourceType.MANUAL;

    @Column(name = "source_sample_id", length = 191)
    private String sourceSampleId;

    @Column(name = "notes", length = 500)
    private String notes;

    @Column(name = "seasoning_revision", nullable = false)
    @Builder.Default
    private Long seasoningRevision = 0L;

    /** Immutable Workflow revision selected while configuring this BOM version. */
    @Column(name = "workflow_revision_id")
    private Long workflowRevisionId;

    @Column(name = "workflow_id")
    private Long workflowId;

    @Column(name = "workflow_definition_version")
    private Integer workflowDefinitionVersion;

    @Column(name = "workflow_revision_hash", length = 64)
    private String workflowRevisionHash;

    @Column(name = "workflow_schema_version")
    private Integer workflowSchemaVersion;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "workflow_nodes_snapshot_json", columnDefinition = "jsonb")
    private String workflowNodesSnapshotJson;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "workflow_edges_snapshot_json", columnDefinition = "jsonb")
    private String workflowEdgesSnapshotJson;

    /** One shared recipe plus all terminal Output Recipes for one immutable Workflow revision. */
    @Column(name = "bom_family_id", length = 64)
    private String bomFamilyId;

    /** MAIN Output Recipe that owns family-shared raw material and process auxiliary rules. */
    @Column(name = "shared_recipe_id", length = 191)
    private String sharedRecipeId;

    /** Stable FINISHED_GOOD Cell selected for this Output Recipe. */
    @Column(name = "target_terminal_node_id", length = 128)
    private String targetTerminalNodeId;

    @Enumerated(EnumType.STRING)
    @Column(name = "output_role", length = 24)
    private OutputRole outputRole;

    /** Percentage of pre-split shared cost allocated to this terminal output. */
    @Column(name = "cost_allocation_ratio", precision = 7, scale = 4)
    private BigDecimal costAllocationRatio;

    @OneToMany(mappedBy = "recipe", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @OrderBy("sortOrder ASC")
    @Builder.Default
    private List<BomRecipeItem> items = new ArrayList<>();

    /** 调料明细 (注射段+熟制段), 折叠自 recipe_ingredients. SKU 级挂法, 同 {@link #items}. */
    @OneToMany(mappedBy = "recipe", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @OrderBy("seq ASC")
    @Builder.Default
    private List<BomSeasoningItem> seasoningItems = new ArrayList<>();

    public enum Status { DRAFT, ACTIVE, ARCHIVED }

    public enum SourceType { MANUAL, SAMPLE_AUTOGEN, AI_GENERATED, IMPORTED }

    public enum OutputRole { MAIN, CO_PRODUCT, BY_PRODUCT }
}
