package com.cretas.aims.service.material.impl;

import com.cretas.aims.dto.material.CreateMaterialCodeSegmentRequest;
import com.cretas.aims.dto.material.MaterialCodeSegmentDTO;
import com.cretas.aims.entity.material.MaterialCodeSegment;
import com.cretas.aims.exception.BusinessException;
import com.cretas.aims.exception.ResourceNotFoundException;
import com.cretas.aims.repository.RawMaterialTypeRepository;
import com.cretas.aims.repository.material.MaterialCodeSegmentRepository;
import com.cretas.aims.service.material.MaterialCodeSegmentService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.text.Normalizer;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

/** Material taxonomy service. Node IDs are generated by the database and never user-maintained. */
@Slf4j
@Service
@RequiredArgsConstructor
public class MaterialCodeSegmentServiceImpl implements MaterialCodeSegmentService {

    private final MaterialCodeSegmentRepository repo;
    private final RawMaterialTypeRepository materialTypeRepository;

    @Override
    public List<MaterialCodeSegmentDTO> listByLevel(String factoryId, short level) {
        validateLevel(level);
        return repo.findByFactoryIdAndLevelOrderBySortOrderAscIdAsc(factoryId, level)
                .stream().map(this::toDTO).toList();
    }

    @Override
    public List<MaterialCodeSegmentDTO> getTree(String factoryId) {
        List<MaterialCodeSegment> all = repo.findByFactoryIdOrderBySortOrderAscIdAsc(factoryId);
        Map<Long, List<MaterialCodeSegmentDTO>> byParent = all.stream()
                .filter(node -> node.getParentId() != null)
                .map(this::toDTO)
                .collect(Collectors.groupingBy(MaterialCodeSegmentDTO::getParentId));

        List<MaterialCodeSegmentDTO> roots = all.stream()
                .filter(node -> node.getLevel() != null && node.getLevel() == 1)
                .map(this::toDTO)
                .toList();
        for (MaterialCodeSegmentDTO root : roots) {
            List<MaterialCodeSegmentDTO> children = byParent.getOrDefault(root.getId(), new ArrayList<>());
            for (MaterialCodeSegmentDTO child : children) {
                List<MaterialCodeSegmentDTO> leaves = byParent.getOrDefault(child.getId(), new ArrayList<>());
                child.setChildren(leaves.isEmpty() ? null : leaves);
            }
            root.setChildren(children.isEmpty() ? null : children);
        }
        return roots;
    }

    @Override
    @Transactional
    public MaterialCodeSegmentDTO create(String factoryId, CreateMaterialCodeSegmentRequest req) {
        short level = requireLevel(req.getLevel());
        Long parentId = validateParent(factoryId, level, req.getParentId());
        String label = requireLabel(req.getSegmentLabel());
        String normalizedLabel = normalizeLabel(label);
        rejectDuplicateLabel(factoryId, level, parentId, normalizedLabel, null);

        MaterialCodeSegment entity = MaterialCodeSegment.builder()
                .factoryId(factoryId)
                .level(level)
                .segmentLabel(label)
                .normalizedLabel(normalizedLabel)
                .parentId(parentId)
                .sortOrder(req.getSortOrder() == null ? 0 : req.getSortOrder())
                .isActive(req.getIsActive() == null || req.getIsActive())
                .build();
        entity.setCreatedAt(LocalDateTime.now());
        entity.setUpdatedAt(LocalDateTime.now());
        try {
            entity = repo.saveAndFlush(entity);
        } catch (DataIntegrityViolationException conflict) {
            throw duplicateLabel(label);
        }
        log.info("创建物料分类 factoryId={} id={} label={}", factoryId, entity.getId(), label);
        return toDTO(entity);
    }

    @Override
    @Transactional
    public MaterialCodeSegmentDTO update(String factoryId, Long id, CreateMaterialCodeSegmentRequest req) {
        MaterialCodeSegment entity = requireOwned(factoryId, id);
        if (req.getLevel() != null && !req.getLevel().equals(entity.getLevel())) {
            throw new BusinessException(400, "分类层级创建后不可修改").withHintTarget("level");
        }
        if (req.getParentId() != null && !req.getParentId().equals(entity.getParentId())) {
            throw new BusinessException(400, "上级分类创建后不可修改")
                    .withHint("需要重新归类时，请新建分类并停用旧分类")
                    .withHintTarget("parentId");
        }

        String label = req.getSegmentLabel() == null
                ? entity.getSegmentLabel() : requireLabel(req.getSegmentLabel());
        String normalizedLabel = normalizeLabel(label);
        rejectDuplicateLabel(factoryId, entity.getLevel(), entity.getParentId(), normalizedLabel, entity.getId());

        entity.setSegmentLabel(label);
        entity.setNormalizedLabel(normalizedLabel);
        if (req.getSortOrder() != null) entity.setSortOrder(req.getSortOrder());
        if (req.getIsActive() != null) entity.setIsActive(req.getIsActive());
        entity.setUpdatedAt(LocalDateTime.now());
        try {
            return toDTO(repo.saveAndFlush(entity));
        } catch (DataIntegrityViolationException conflict) {
            throw duplicateLabel(label);
        }
    }

    @Override
    @Transactional
    public void delete(String factoryId, Long id) {
        MaterialCodeSegment entity = requireOwned(factoryId, id);
        long liveChildren = repo.countByFactoryIdAndParentId(factoryId, id);
        if (liveChildren > 0) {
            throw new BusinessException(409, "该分类下还有 " + liveChildren + " 个未删除的下级分类")
                    .withHint("请先处理下级分类；若只是不想再使用，请改为停用")
                    .withHintTarget("id");
        }
        long materialsInUse = materialTypeRepository
                .countActiveByFactoryIdAndClassificationSegmentId(factoryId, id);
        if (materialsInUse > 0) {
            throw new BusinessException(409, "该分类仍被 " + materialsInUse + " 个在用物料引用")
                    .withHint("请改为停用，历史物料的分类归属会继续保留")
                    .withHintTarget("id");
        }
        entity.setDeletedAt(LocalDateTime.now());
        repo.save(entity);
        log.info("软删除物料分类 factoryId={} id={} label={}", factoryId, id, entity.getSegmentLabel());
    }

    @Override
    @Transactional(readOnly = true)
    public List<MaterialCodeSegmentDTO> listDeleted(String factoryId) {
        return repo.findDeletedByFactoryId(factoryId).stream().map(this::toDTO).toList();
    }

    @Override
    @Transactional
    public MaterialCodeSegmentDTO restore(String factoryId, Long id) {
        MaterialCodeSegment entity = repo.findByIdIncludingDeleted(id)
                .orElseThrow(() -> new ResourceNotFoundException("物料分类不存在: id=" + id));
        if (!factoryId.equals(entity.getFactoryId())) {
            throw new BusinessException(403, "无权限操作此分类");
        }
        if (entity.getDeletedAt() == null) {
            throw new BusinessException(400, "该分类未被删除，无需恢复").withHintTarget("id");
        }
        if (entity.getParentId() != null && repo.findByIdAndFactoryId(entity.getParentId(), factoryId).isEmpty()) {
            throw new BusinessException(409, "上级分类已删除，请先恢复上级")
                    .withHint("恢复顺序：先一级，再二级，最后三级")
                    .withHintTarget("parentId");
        }
        rejectDuplicateLabel(factoryId, entity.getLevel(), entity.getParentId(),
                normalizeLabel(entity.getSegmentLabel()), entity.getId());
        repo.restoreById(id);
        entity.setDeletedAt(null);
        log.info("恢复物料分类 factoryId={} id={} label={}", factoryId, id, entity.getSegmentLabel());
        return toDTO(entity);
    }

    @Override
    public boolean hasSegmentDictionary(String factoryId) {
        return repo.countByFactoryIdAndLevel(factoryId, (short) 1) > 0;
    }

    MaterialCodeSegmentDTO toDTO(MaterialCodeSegment entity) {
        return MaterialCodeSegmentDTO.builder()
                .id(entity.getId())
                .factoryId(entity.getFactoryId())
                .level(entity.getLevel())
                .segmentLabel(entity.getSegmentLabel())
                .parentId(entity.getParentId())
                .sortOrder(entity.getSortOrder())
                .isActive(entity.getIsActive())
                .build();
    }

    private MaterialCodeSegment requireOwned(String factoryId, Long id) {
        return repo.findByIdAndFactoryId(id, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("物料分类不存在: id=" + id));
    }

    private Long validateParent(String factoryId, short level, Long parentId) {
        validateLevel(level);
        if (level == 1) {
            if (parentId != null) {
                throw new BusinessException(400, "一级分类不能选择上级").withHintTarget("parentId");
            }
            return null;
        }
        if (parentId == null) {
            throw new BusinessException(400, "二级或三级分类必须选择上级分类")
                    .withHintTarget("parentId");
        }
        MaterialCodeSegment parent = repo.findByIdAndFactoryId(parentId, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("上级分类不存在: id=" + parentId));
        if (parent.getLevel() == null || parent.getLevel() != level - 1
                || !Boolean.TRUE.equals(parent.getIsActive())) {
            throw new BusinessException(400, "请选择启用的直属上级分类").withHintTarget("parentId");
        }
        return parentId;
    }

    private short requireLevel(Short level) {
        if (level == null) {
            throw new BusinessException(400, "请选择分类层级").withHintTarget("level");
        }
        validateLevel(level);
        return level;
    }

    private void validateLevel(short level) {
        if (level < 1 || level > 3) {
            throw new BusinessException(400, "分类层级只能是一级、二级或三级").withHintTarget("level");
        }
    }

    private String requireLabel(String label) {
        if (label == null || label.trim().isEmpty()) {
            throw new BusinessException(400, "分类名称不能为空").withHintTarget("segmentLabel");
        }
        return label.trim();
    }

    private String normalizeLabel(String label) {
        return Normalizer.normalize(label, Normalizer.Form.NFKC)
                .trim().toLowerCase(Locale.ROOT).replaceAll("\\s+", "");
    }

    private void rejectDuplicateLabel(String factoryId, short level, Long parentId,
                                      String normalizedLabel, Long excludeId) {
        long safeExcludeId = excludeId == null ? Long.MIN_VALUE : excludeId;
        if (repo.existsSiblingWithNormalizedLabel(
                factoryId, level, parentId, normalizedLabel, safeExcludeId)) {
            throw duplicateLabel(normalizedLabel);
        }
        // Rows quarantined by the earlier identity migration have normalized_label = NULL.
        // Compare their labels in memory so new writes still cannot duplicate them.
        boolean legacyConflict = repo.findSiblings(factoryId, parentId).stream()
                .anyMatch(existing -> !existing.getId().equals(excludeId)
                        && normalizeLabel(existing.getSegmentLabel()).equals(normalizedLabel));
        if (legacyConflict) throw duplicateLabel(normalizedLabel);
    }

    private BusinessException duplicateLabel(String label) {
        return new BusinessException(409, "同一上级分类下已存在名称为「" + label + "」的分类")
                .withHint("请直接使用已有分类，或填写语义不同的名称")
                .withHintTarget("segmentLabel");
    }
}
