package com.cretas.aims.service.impl;

import com.cretas.aims.dto.equipment.CreateEquipmentRequest;
import com.cretas.aims.dto.equipment.EquipmentDTO;
import com.cretas.aims.entity.FactoryEquipment;
import com.cretas.aims.repository.BatchEquipmentUsageRepository;
import com.cretas.aims.repository.EquipmentMaintenanceRepository;
import com.cretas.aims.repository.EquipmentRepository;
import com.cretas.aims.repository.UserRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDate;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

/**
 * module-verify 2026-07-03 Bug 1 + Bug 4 回归测试:
 *  1. web-admin 用 "equipmentCode" 字段名 POST 设备编号, 后端 DTO 字段是 "code" —
 *     JsonAlias 修复前会被静默丢弃, 后端总是 auto-generate 编号 (设备编号必填项形同虚设)。
 *  2. RN 移动端沿用旧字段名 "code", 修复后必须仍然可用 (不能顾此失彼)。
 *  3. 创建设备时给了维护间隔, nextMaintenanceDate 应按间隔换算, 不是硬编码 30 天。
 */
@ExtendWith(MockitoExtension.class)
class EquipmentServiceImplCreateTest {

    @Mock private EquipmentRepository equipmentRepository;
    @Mock private EquipmentMaintenanceRepository maintenanceRepository;
    @Mock private BatchEquipmentUsageRepository usageRepository;
    @Mock private UserRepository userRepository;

    @InjectMocks
    private EquipmentServiceImpl service;

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper()
            .registerModule(new com.fasterxml.jackson.datatype.jsr310.JavaTimeModule());

    @Test
    void jsonAlias_equipmentCode_deserializesIntoCodeField() throws Exception {
        // web-admin payload shape
        String json = "{\"name\":\"卤煮锅1号\",\"equipmentCode\":\"EQ-WEB-001\"}";
        CreateEquipmentRequest req = OBJECT_MAPPER.readValue(json, CreateEquipmentRequest.class);
        assertThat(req.getCode()).isEqualTo("EQ-WEB-001");
    }

    @Test
    void jsonAlias_legacyCodeField_stillWorks() throws Exception {
        // RN mobile payload shape (legacy field name) must still deserialize correctly
        String json = "{\"name\":\"卤煮锅1号\",\"code\":\"EQ-RN-002\"}";
        CreateEquipmentRequest req = OBJECT_MAPPER.readValue(json, CreateEquipmentRequest.class);
        assertThat(req.getCode()).isEqualTo("EQ-RN-002");
    }

    @Test
    void createEquipment_withExplicitCode_persistsThatCodeNotAutoGenerated() {
        CreateEquipmentRequest req = new CreateEquipmentRequest();
        req.setName("卤煮锅1号");
        req.setCode("EQ-USER-TYPED");

        when(equipmentRepository.save(any(FactoryEquipment.class))).thenAnswer(i -> {
            FactoryEquipment e = i.getArgument(0);
            if (e.getId() == null) e.setId(1L); // mimic DB IDENTITY assignment on first save
            when(equipmentRepository.findByIdAndFactoryId(e.getId(), e.getFactoryId())).thenReturn(Optional.of(e));
            return e;
        });

        EquipmentDTO dto = service.createEquipment("F006", req, 1L);

        ArgumentCaptor<FactoryEquipment> captor = ArgumentCaptor.forClass(FactoryEquipment.class);
        org.mockito.Mockito.verify(equipmentRepository).save(captor.capture());
        assertThat(captor.getValue().getCode()).isEqualTo("EQ-USER-TYPED");
        assertThat(captor.getValue().getEquipmentCode()).isEqualTo("EQ-USER-TYPED");
        assertThat(dto.getEquipmentCode()).isEqualTo("EQ-USER-TYPED");
    }

    @Test
    void createEquipment_withBlankCode_fallsBackToAutoGenerated() {
        CreateEquipmentRequest req = new CreateEquipmentRequest();
        req.setName("卤煮锅1号");
        req.setCode("   "); // blank → should still auto-generate

        when(equipmentRepository.save(any(FactoryEquipment.class))).thenAnswer(i -> {
            FactoryEquipment e = i.getArgument(0);
            if (e.getId() == null) e.setId(1L); // mimic DB IDENTITY assignment on first save
            when(equipmentRepository.findByIdAndFactoryId(e.getId(), e.getFactoryId())).thenReturn(Optional.of(e));
            return e;
        });

        EquipmentDTO dto = service.createEquipment("F006", req, 1L);

        assertThat(dto.getEquipmentCode()).isNotBlank();
        assertThat(dto.getEquipmentCode().trim()).isNotEqualTo("");
    }

    @Test
    void createEquipment_withMaintenanceInterval_computesNextMaintenanceDateFromInterval() {
        CreateEquipmentRequest req = new CreateEquipmentRequest();
        req.setName("卤煮锅1号");
        req.setCode("EQ-MTN-001");
        req.setMaintenanceIntervalHours(24 * 90); // 90 天间隔

        when(equipmentRepository.save(any(FactoryEquipment.class))).thenAnswer(i -> {
            FactoryEquipment e = i.getArgument(0);
            if (e.getId() == null) e.setId(1L); // mimic DB IDENTITY assignment on first save
            when(equipmentRepository.findByIdAndFactoryId(e.getId(), e.getFactoryId())).thenReturn(Optional.of(e));
            return e;
        });

        EquipmentDTO dto = service.createEquipment("F006", req, 1L);

        assertThat(dto.getNextMaintenanceDate()).isEqualTo(LocalDate.now().plusDays(90));
    }

    @Test
    void updateEquipment_backfillsNextMaintenanceDate_whenNeverSet() {
        FactoryEquipment existing = new FactoryEquipment();
        existing.setId(9L);
        existing.setFactoryId("F006");
        existing.setEquipmentName("旧设备");
        existing.setCode("EQ-OLD-009");
        existing.setEquipmentCode("EQ-OLD-009");
        existing.setStatus("active");
        existing.setVersion(1);
        // 从未设置过 nextMaintenanceDate (legacy equipment created before interval field existed)
        existing.setNextMaintenanceDate(null);

        when(equipmentRepository.findByIdAndFactoryId(9L, "F006")).thenReturn(Optional.of(existing));
        when(equipmentRepository.save(any(FactoryEquipment.class))).thenAnswer(i -> {
            FactoryEquipment e = i.getArgument(0);
            if (e.getId() == null) e.setId(1L); // mimic DB IDENTITY assignment on first save
            return e;
        });

        CreateEquipmentRequest req = new CreateEquipmentRequest();
        req.setMaintenanceIntervalHours(24 * 30); // 30 天间隔, 首次补填

        EquipmentDTO dto = service.updateEquipment("F006", "9", req);

        assertThat(dto.getNextMaintenanceDate()).isEqualTo(LocalDate.now().plusDays(30));
    }
}
