/**
 * BOM API — includes:
 *   - BOM Recipe lifecycle (BomRecipeController): activate DRAFT → ACTIVE
 *   - BOM Yield Estimate (BomYieldEstimateController): Phase B/C endpoints
 *   - BOM Seasoning (BomSeasoningController): 调料配方 folded into BOM subsystem
 *
 * Base URL is /api/mobile (set in request.ts baseURL).
 * Endpoint prefix: /{factoryId}/bom/recipes/{recipeId}/...
 */
import { del, get, post, put } from './request';

// =========================================================================
// BOM Recipe — status types + activate API
// =========================================================================

/** BomRecipe.Status enum values (mirrors backend BomRecipe.Status) */
export type BomRecipeStatus = 'DRAFT' | 'ACTIVE' | 'ARCHIVED';

/**
 * Minimal BomRecipe shape returned by the list/activate endpoints.
 * Fields match BomRecipe entity JSON serialization (camelCase via Jackson).
 */
export interface BomRecipeSummary {
  id: string;
  factoryId: string;
  recipeCode: string;
  productTypeId: string;
  productName: string;
  version: number;
  isCurrent: boolean;
  status: BomRecipeStatus;
  overallYieldRate?: number | null;
  outputQuantityPerUnit?: number | null;
  outputUnit?: string | null;
  netContentQuantity?: number | null;
  netContentUnit?: string | null;
  notes?: string | null;
  activatedAt?: string | null;
  activatedBy?: number | null;
  totalCost?: number | null;
  totalMaterialCost?: number | null;
  totalLaborCost?: number | null;
  totalOverheadCost?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  workflowRevisionId?: number | null;
  workflowId?: number | null;
  workflowOwnerProductTypeId?: string | null;
  workflowDefinitionVersion?: number | null;
  workflowRevisionHash?: string | null;
  bomFamilyId?: string | null;
  sharedRecipeId?: string | null;
  targetTerminalNodeId?: string | null;
  outputRole?: 'MAIN' | 'CO_PRODUCT' | 'BY_PRODUCT' | null;
  costAllocationRatio?: number | null;
  byproductNrvUnitPrice?: number | null;
  items?: BomRecipeItemView[];
}

export interface WorkflowRevisionCandidate {
  revisionId?: number | null;
  workflowId: number;
  definitionVersion?: number | null;
  revisionNumber?: number | null;
  revisionHash: string;
  status: 'DRAFT' | 'PUBLISHED' | string;
  savedAt?: string | null;
  processCount?: number | null;
  enabled?: boolean;
  compatible: boolean;
  incompatibilityReason?: string | null;
  recommended?: boolean;
}

export interface BomWorkflowRevisionPinPayload {
  revisionId?: number | null;
  workflowId?: number | null;
  revisionHash: string;
}

export interface BomRecipeItemPayload {
  materialTypeId: string;
  /** Stable Workflow input identity generated by the pinned target DAG slice. */
  workflowMaterialNodeId?: string | null;
  workflowInputPortId?: string | null;
  workflowEdgeId?: string | null;
  costScope?: 'SHARED' | 'OUTPUT_GROUP' | 'OUTPUT_EXCLUSIVE' | null;
  /** Server-owned canonical output membership; clients only round-trip it. */
  costScopeKey?: string | null;
  /** RAW/AUXILIARY 仅建立物料关系时可空；PACKAGING 必须提供固定用量。 */
  standardQuantity: number | null;
  yieldRate?: number | null;
  unit: string;
  unitPrice?: number | null;
  taxRate?: number | null;
  materialCategory?: string | null;
  sortOrder?: number | null;
  isOptional?: boolean | null;
  /** @deprecated legacy free-text grouping; new writes use substitutes. */
  substituteGroup?: string | null;
  packagingSpecId?: string | null;
  packagingRole?: string | null;
  naturalQuantity?: number | null;
  substitutes?: BomSubstituteInput[];
  remark?: string | null;
  perPortion?: boolean | null;
  semiFinishedRefCode?: string | null;
  subProductTypeId?: string | null;
}

export interface BomRecipeItemView extends BomRecipeItemPayload {
  id: number;
  recipeId: string;
  factoryId: string;
  materialName?: string | null;
  actualQuantity?: number | null;
  itemCost?: number | null;
  priceUnit?: string | null;
  quantityToPriceFactor?: number | null;
  primaryCode?: string | null;
  primaryCodeRef?: string | null;
  packagingSpecNameSnapshot?: string | null;
  naturalUnit?: string | null;
  packagingPackageUnitSnapshot?: string | null;
  packagingBaseUnitSnapshot?: string | null;
  packagingConversionFactorSnapshot?: number | null;
  substituteDetails?: BomItemSubstituteView[];
}

export interface BomSubstituteInput {
  materialTypeId: string;
  conversionFactor?: number | null;
}

export interface BomItemSubstituteView {
  id: string;
  recipeId: string;
  parentKind: 'RECIPE_ITEM' | 'SEASONING_ITEM';
  parentRecipeItemId?: number | null;
  parentSeasoningItemId?: number | null;
  parentMaterialTypeId: string;
  parentMaterialName?: string | null;
  materialCategory: string;
  workProcessId?: string | null;
  packagingSpecId?: string | null;
  packagingRole?: string | null;
  substituteMaterialTypeId: string;
  substituteMaterialCode?: string | null;
  substituteMaterialName?: string | null;
  parentUnit?: string | null;
  substituteUnit?: string | null;
  conversionFactor: number;
  conversionExplicit?: boolean;
}

export interface ProductPackagingSpecView {
  id: string;
  name: string;
  packageUnit: string;
  baseUnit: string;
  conversionFactor: number;
  defaultSpec?: boolean;
  active?: boolean;
  sortOrder?: number;
}

export interface ProductConfigurationReadinessIssue {
  code: string;
  message: string;
  target?: string | null;
}

export interface ProductConfigurationReadiness {
  factoryId: string;
  productTypeId: string;
  stage: string;
  bomState: string;
  workflowDraftComplete: boolean;
  bomConfigurable: boolean;
  bomComplete: boolean;
  bomActive: boolean;
  workflowEnabled: boolean;
  issues: ProductConfigurationReadinessIssue[];
}

export interface CreateBomRecipeRequest {
  productTypeId: string;
  productName?: string | null;
  overallYieldRate?: number | null;
  /** @deprecated server derives output identity from the SKU */
  outputQuantityPerUnit?: number;
  /** @deprecated server derives output identity from the SKU */
  outputUnit?: string;
  sourceType?: 'MANUAL' | 'SAMPLE_AUTOGEN' | 'AI_GENERATED' | 'IMPORTED';
  sourceSampleId?: string | null;
  items: BomRecipeItemPayload[];
  notes?: string | null;
}

export interface UpdateBomRecipeRequest {
  productName?: string | null;
  overallYieldRate?: number | null;
  outputQuantityPerUnit?: number | null;
  outputUnit?: string | null;
  items?: BomRecipeItemPayload[];
  notes?: string | null;
}

export interface BomCopySharedProcess {
  workProcessId: string;
  processName: string;
  targetOrder?: number | null;
}

export interface BomCopyItemRule {
  id: number;
  materialTypeId: string;
  materialName: string;
  materialCategory?: string | null;
  standardQuantity?: number | null;
  unit?: string | null;
  sortOrder?: number | null;
  optional?: boolean | null;
  substituteGroup?: string | null;
  remark?: string | null;
  perPortion?: boolean | null;
  semiFinishedRefCode?: string | null;
  subProductTypeId?: string | null;
  primaryCode?: string | null;
}

export interface BomCopySeasoningRule {
  id: number;
  workProcessId: string;
  workProcessName?: string | null;
  materialTypeId?: string | null;
  name: string;
  section?: string | null;
  dosagePerKgG?: number | null;
  seq?: number | null;
  countInSeasoning?: boolean | null;
  remark?: string | null;
}

export interface BomCopyInjectionConfigRule {
  id: number;
  workProcessId: string;
  workProcessName?: string | null;
  injectionAmountKg: number;
  notes?: string | null;
}

/** A current BOM from a finished product that shares the target's raw source and processes. */
export interface BomCopyCandidate {
  sourceProductTypeId: string;
  sourceProductName: string;
  sourceRecipeId: string;
  sourceRecipeCode?: string | null;
  sourceRecipeVersion?: number | null;
  rawRootMaterialTypeId?: string | null;
  sharedProcesses: BomCopySharedProcess[];
  bomItems: BomCopyItemRule[];
  seasoningItems: BomCopySeasoningRule[];
  processInjectionConfigs: BomCopyInjectionConfigRule[];
}

export interface CopyBomToProductRequest {
  targetProductTypeId: string;
  sourceRecipeId: string;
  recipeItemIds: number[];
  seasoningItemIds: number[];
  processInjectionConfigIds: number[];
}

const recipeBase = (factoryId: string) => `/${factoryId}/bom/recipes`;

export const bomRecipeApi = {
  getProductConfigurationReadiness: (
    factoryId: string,
    productTypeId: string,
    recipeId?: string | null,
  ) => get<ProductConfigurationReadiness>(
    `/${factoryId}/product-configuration-readiness/${productTypeId}`,
    {
      params: recipeId ? { recipeId } : {},
      // BOM 页面按产品 single-flight，并按 errorCode 在当前导航内呈现一次。
      // 关闭全局提示，避免初始化阶段的并发请求重复弹出同一富错误。
      _silent: true,
    },
  ),

  getProductPackagingSpecs: (factoryId: string, productTypeId: string) =>
    get<ProductPackagingSpecView[]>(`/${factoryId}/product-types/${productTypeId}/packaging-specs`),
  /**
   * 分页查询 BOM 配方列表, 可按 status 过滤.
   * 对应: GET /api/mobile/{factoryId}/bom/recipes
   */
  listRecipes: (
    factoryId: string,
    options?: { status?: BomRecipeStatus; page?: number; size?: number },
  ) =>
    get<{ content: BomRecipeSummary[]; totalElements: number; totalPages: number }>(
      recipeBase(factoryId),
      { params: { ...options } },
    ),

  getDetail: (factoryId: string, recipeId: string) =>
    get<BomRecipeSummary>(`${recipeBase(factoryId)}/${recipeId}`),

  listSubstitutes: (factoryId: string, recipeId: string) =>
    get<BomItemSubstituteView[]>(`${recipeBase(factoryId)}/${recipeId}/substitutes`),

  listWorkflowRevisions: (factoryId: string, recipeId: string) =>
    get<WorkflowRevisionCandidate[]>(`${recipeBase(factoryId)}/${recipeId}/workflow-revisions`),

  pinWorkflowRevision: (factoryId: string, recipeId: string, payload: BomWorkflowRevisionPinPayload) =>
    put<BomRecipeSummary>(`${recipeBase(factoryId)}/${recipeId}/workflow-revisions/pin`, payload),

  /** Upgrade a BOM family to the newest provably compatible saved Workflow draft. */
  upgradeWorkflowRevision: (factoryId: string, recipeId: string) =>
    post<BomRecipeSummary>(`${recipeBase(factoryId)}/${recipeId}/workflow-revisions/upgrade-latest`, null),

  getFamilyOutputCosting: (factoryId: string, recipeId: string) =>
    get<BomFamilyOutputCosting>(`${recipeBase(factoryId)}/${recipeId}/family-output-costing`),

  updateFamilyOutputCosting: (
    factoryId: string,
    recipeId: string,
    payload: UpdateBomFamilyOutputCostingRequest,
  ) => put<BomFamilyOutputCosting>(
    `${recipeBase(factoryId)}/${recipeId}/family-output-costing`,
    payload,
  ),

  /** Idempotently reuse/create the one editable draft for a factory-scoped SKU. */
  ensureDraft: (factoryId: string, productTypeId: string) =>
    post<BomRecipeSummary>(`${recipeBase(factoryId)}/ensure-draft`, { productTypeId }),

  getCurrentByProduct: (factoryId: string, productTypeId: string) =>
    get<BomRecipeSummary>(`${recipeBase(factoryId)}/by-product/${productTypeId}/current`),

  getVersionsByProduct: (factoryId: string, productTypeId: string) =>
    get<BomRecipeSummary[]>(`${recipeBase(factoryId)}/by-product/${productTypeId}/versions`),

  /**
   * 创建 BOM 配方草稿.
   * 对应: POST /api/mobile/{factoryId}/bom/recipes
   */
  create: (factoryId: string, req: CreateBomRecipeRequest) =>
    post<BomRecipeSummary>(recipeBase(factoryId), req),

  /**
   * 更新 BOM 配方草稿.
   * 对应: PUT /api/mobile/{factoryId}/bom/recipes/{recipeId}
   */
  update: (factoryId: string, recipeId: string, req: UpdateBomRecipeRequest) =>
    put<BomRecipeSummary>(`${recipeBase(factoryId)}/${recipeId}`, req),

  addItem: (factoryId: string, recipeId: string, item: BomRecipeItemPayload) =>
    post<BomRecipeItemView>(`${recipeBase(factoryId)}/${recipeId}/items`, item),

  updateItem: (factoryId: string, itemId: number, item: BomRecipeItemPayload) =>
    put<BomRecipeItemView>(`${recipeBase(factoryId)}/items/${itemId}`, item),

  removeItem: (factoryId: string, itemId: number) =>
    del<void>(`${recipeBase(factoryId)}/items/${itemId}`),

  /** 克隆任意历史版本为可编辑草稿。 */
  clone: (factoryId: string, recipeId: string) =>
    post<BomRecipeSummary>(`${recipeBase(factoryId)}/${recipeId}/clone`, null),

  /** Find current BOMs from same-source finished products with shared workflow processes. */
  getCopyCandidates: (factoryId: string, targetProductTypeId: string) =>
    get<BomCopyCandidate[]>(`${recipeBase(factoryId)}/copy-candidates`, {
      params: { targetProductTypeId },
      _silent: true,
    }),

  /** Copy only explicitly selected rules into a new editable DRAFT for the target product. */
  copyToProduct: (factoryId: string, req: CopyBomToProductRequest) =>
    post<BomRecipeSummary>(`${recipeBase(factoryId)}/copy-to-draft`, req),

  /** 删除草稿或历史未生效版本；当前 ACTIVE 版本由后端拒绝。 */
  removeDraft: (factoryId: string, recipeId: string) =>
    del<void>(`${recipeBase(factoryId)}/${recipeId}`),

  /**
   * 激活草稿或任意历史正式版本，使其成为唯一 ACTIVE/current 配方。
   * 原生效版本转为历史未生效；仅之后新建计划读取新快照。
   * 对应: POST /api/mobile/{factoryId}/bom/recipes/{recipeId}/activate
   */
  activate: (factoryId: string, recipeId: string, operatorId?: number | null) =>
    post<BomRecipeSummary>(
      `${recipeBase(factoryId)}/${recipeId}/activate`,
      null,
      { params: operatorId != null ? { operatorId } : {} },
    ),
};

/** 单个 BOM Item 出成率评估响应 */
export interface YieldEstimateResponse {
  productTypeId: string;
  materialCategory: string;
  /** 建议的成品含量 (克), null = 无法推断 */
  suggestedStandardQuantity: number | null;
  /** 建议出成率 (百分比, 如 61.5 表示 61.5%), null = 无数据 */
  suggestedYieldRate: number | null;
  /** 参考批次数量 */
  sampleCount: number;
  /** 最近 N 批次的出成率最低值 */
  yieldMin: number | null;
  /** 最近 N 批次的出成率最高值 */
  yieldMax: number | null;
  /** 数据来源 */
  source: 'BATCH_REPORTING' | 'STANDARD_WEIGHT_ONLY' | 'NONE';
  /**
   * null = 无异常
   * INSUFFICIENT_SAMPLES = 样本不足
   * NO_GRAMS_PER_UNIT = 产品未配置标准克重
   */
  reason: 'INSUFFICIENT_SAMPLES' | 'NO_GRAMS_PER_UNIT' | null;
  /** 操作提示 (可含跳转指引) */
  actionHint: string | null;
}

/** 一键重算预览 — 单行 */
export interface RecalculatePreviewRow {
  productTypeId: string;
  productName: string;
  recipeId: string;
  materialName: string;
  /** 当前配置的出成率, null 表示未填 */
  currentYieldRate: number | null;
  /** 建议出成率, null 表示数据不足 */
  suggestedYieldRate: number | null;
  sampleCount: number;
  /**
   * UPDATABLE          = 有足够样本可更新
   * INSUFFICIENT_SAMPLES = 样本不足, 不可更新
   * SKIP               = 跳过 (无主原料 / 无批次报工等)
   */
  status: 'UPDATABLE' | 'INSUFFICIENT_SAMPLES' | 'SKIP';
}

/** 一键重算应用请求体 — 单行 */
export interface RecalculateApplyItem {
  recipeId: string;
  yieldRate: number;
  /** 乐观锁: 预览时拿到的当前出成率, null 表示预览时未填 (原值也为 null) */
  expectedCurrentYieldRate: number | null;
}

/** 一键重算应用响应 */
export interface RecalculateApplyResponse {
  applied: number;
  changeLogIds: string[];
}

/**
 * 409 Conflict 响应体 — 数据已变化 (乐观锁冲突)
 * 后端在应用时发现 DB 值已被其他操作修改时返回此结构。
 */
export interface RecalculateApplyStaleResponse {
  staleRows: Array<{
    recipeId: string;
    dbCurrent: number | null;
    expected: number | null;
  }>;
  message: string;
}

const base = (factoryId: string) => `/${factoryId}/bom/yield-estimate`;

export const bomYieldEstimateApi = {
  /**
   * 获取单个产品的出成率评估建议.
   * @param productTypeId  产品 ID
   * @param materialCategory  物料类别 (RAW | AUXILIARY | PACKAGING), 通常传 'RAW'
   */
  getEstimate: (
    factoryId: string,
    productTypeId: string,
    materialCategory: string = 'RAW',
  ) =>
    get<YieldEstimateResponse>(base(factoryId), {
      params: { productTypeId, materialCategory },
    }),

  /**
   * 一键重算预览 — 返回所有可更新 BOM 的建议出成率, 不写数据库.
   * @param productTypeIds  可选: 仅针对指定产品, 不传则全工厂扫描
   */
  recalculatePreview: (
    factoryId: string,
    productTypeIds?: string[],
  ) =>
    post<RecalculatePreviewRow[]>(`${base(factoryId)}/recalculate-preview`, {
      ...(productTypeIds ? { productTypeIds } : {}),
    }),

  /**
   * 一键重算应用 — 写入用户勾选的行, 生成变更日志.
   * @param items  recipeId + yieldRate 列表
   */
  recalculateApply: (
    factoryId: string,
    items: RecalculateApplyItem[],
  ) =>
    post<RecalculateApplyResponse>(`${base(factoryId)}/recalculate-apply`, items),
};

// =========================================================================
// BOM Seasoning — 调料配方 (注射+熟制) folded into BOM subsystem
// Endpoints:  /{factoryId}/bom/recipes/by-product/{productTypeId}/seasoning
//             /{factoryId}/bom/recipes/{recipeId}/seasoning  (GET + PUT)
//             /{factoryId}/bom/recipes/{recipeId}/clone       (POST)
// =========================================================================

/** One seasoning ingredient item (mirrors BomSeasoningItem entity) */
export interface BomSeasoningItem {
  id?: string | null;
  recipeId?: string | null;
  factoryId?: string | null;
  /** 该调料所属工序 (ProductWorkProcess.workProcessId) — 调料配方按工序分组的锚点键 */
  workProcessId: string;
  /** 物料主数据引用；历史自由文本行可能为空，新保存行必须提供。 */
  materialTypeId?: string | null;
  /** 仅用于前端展示，保存时后端以物料主数据为准。 */
  unit?: string | null;
  /** INJECTION = 注射段; COOKING = 熟制段 */
  section: 'INJECTION' | 'COOKING';
  seq: number;
  name: string;
  dosagePerKgG: number | null;
  /** 后续工序带入比例；旧数据或不涉及续锅时为空。 */
  subsequentPotRatio?: number | null;
  priceSource1: number | null;
  priceSource2: number | null;
  /** false for 老汤 (老汤不计入调料成本) */
  countInSeasoning: boolean;
  remark?: string | null;
}

/** 单个注射工序的绝对注射量。 */
export interface ProcessInjectionConfig {
  workProcessId: string;
  injectionAmountKg: number;
  notes?: string | null;
}

/** Full seasoning response (mirrors BomSeasoningResponse) */
export interface BomSeasoningResponse {
  bomRecipeId: string;
  productTypeId: string;
  productName: string;
  /** DRAFT = 可编辑; ACTIVE / ARCHIVED = 只读 */
  status: BomRecipeStatus;
  seasoningItems: BomSeasoningItem[];
  injectionConfigs: ProcessInjectionConfig[];
}

/** Save request body for PUT /{recipeId}/seasoning */
export interface BomSeasoningSaveRequest {
  seasoningItems: Array<{
    workProcessId: string;
    materialTypeId: string;
    section: 'INJECTION' | 'COOKING';
    seq: number;
    name: string;
    dosagePerKgG: number | null;
    priceSource1: number | null;
    priceSource2: number | null;
    countInSeasoning: boolean;
    remark?: string | null;
    subsequentPotRatio?: number | null;
  }>;
  injectionConfigs: ProcessInjectionConfig[];
}

const seasoningBase = (factoryId: string) => `/${factoryId}/bom/recipes`;

export const bomSeasoningApi = {
  /**
   * 按产品类型加载当前 BOM 的调料配方。
   * 若该产品尚未建 BOM，后端返回 404 { success:false, message:"产品未建 BOM 配方: ..." }。
   */
  getByProduct: (factoryId: string, productTypeId: string) =>
    get<BomSeasoningResponse>(
      `${seasoningBase(factoryId)}/by-product/${productTypeId}/seasoning`,
      // _silent: 无 BOM 时后端返 404, 由组件用 EmptyState 引导建 BOM —
      // 抑制全局 404 toast, 避免 toast + EmptyState 双重提示 (audit R2 Issue 1).
      { _silent: true },
    ),

  /** 按 recipeId 加载调料配方 */
  getById: (factoryId: string, recipeId: string) =>
    get<BomSeasoningResponse>(
      `${seasoningBase(factoryId)}/${recipeId}/seasoning`,
    ),

  /**
   * 保存调料配方（全量替换）。
   * 后端要求 BOM 为 DRAFT 状态，否则抛业务异常。
   */
  save: (factoryId: string, recipeId: string, payload: BomSeasoningSaveRequest) =>
    put<BomSeasoningResponse>(
      `${seasoningBase(factoryId)}/${recipeId}/seasoning`,
      payload,
    ),

  /**
   * 克隆当前 BOM 为新 DRAFT 版本（POST /{recipeId}/clone）。
   * 返回新 BomRecipe（含新 recipeId，status=DRAFT）。
   */
  clone: (factoryId: string, recipeId: string) =>
    post<BomRecipeSummary>(
      `${seasoningBase(factoryId)}/${recipeId}/clone`,
      null,
    ),

  /**
   * 激活 BOM 配方 (DRAFT → ACTIVE, 置为当前版本)。
   * 克隆-编辑后调用使新草稿生效 (POST /{recipeId}/activate).
   */
  activate: (factoryId: string, recipeId: string) =>
    post<BomRecipeSummary>(
      `${seasoningBase(factoryId)}/${recipeId}/activate`,
      null,
    ),

  getWorkspace: (factoryId: string, recipeId: string) =>
    get<SeasoningWorkspace>(`${seasoningBase(factoryId)}/${recipeId}/seasoning/workspace`),

  createBinding: (
    factoryId: string,
    recipeId: string,
    workProcessId: string,
    payload: SeasoningBindingMutation,
  ) => post<SeasoningBindingMutationResponse>(
    `${seasoningBase(factoryId)}/${recipeId}/seasoning/processes/${workProcessId}/bindings`,
    payload,
  ),

  updateBinding: (
    factoryId: string,
    recipeId: string,
    bindingId: number,
    payload: SeasoningBindingMutation,
  ) => put<SeasoningBindingMutationResponse>(
    `${seasoningBase(factoryId)}/${recipeId}/seasoning/bindings/${bindingId}`,
    payload,
  ),

  deleteBinding: (
    factoryId: string,
    recipeId: string,
    bindingId: number,
    expectedRevision: number,
  ) => del<SeasoningBindingMutationResponse>(
    `${seasoningBase(factoryId)}/${recipeId}/seasoning/bindings/${bindingId}`,
    { params: { expectedRevision } },
  ),
};

export interface SeasoningBindingView {
  id: number;
  workflowProcessNodeId: string;
  workProcessId: string;
  materialTypeId: string | null;
  name: string;
  /** Defensive alias for future aggregate DTOs; current backend entity serializes `name`. */
  materialName?: string;
  materialCode?: string | null;
  unit?: string | null;
  dosagePerKgG: number;
  subsequentPotRatio: number | null;
  countInSeasoning: boolean;
  priceSnapshot?: number | null;
  priceSource1?: number | null;
  /** Purchase-reference fallback. It is not an inventory moving-average price. */
  priceSource2?: number | null;
  remark?: string | null;
}

export interface SeasoningProcessView {
  workflowProcessNodeId: string;
  workProcessId: string;
  processOrder: number;
  processName: string;
  processCategory?: string | null;
  /** Pinned Workflow node output basis. Unsupported or ambiguous dimensions are read-only. */
  standardBasisQuantity?: number | null;
  standardBasisUnit?: string | null;
  standardBasisMaterialKind?: 'SEMI_FINISHED' | 'FINISHED_GOOD' | string | null;
  /** @deprecated compatibility with older aggregate responses. */
  basisQuantity?: number | null;
  /** @deprecated compatibility with older aggregate responses. */
  basisUnit?: string | null;
  standardUsageSupported?: boolean;
  costScope?: 'SHARED' | 'OUTPUT_GROUP' | 'OUTPUT_EXCLUSIVE' | string | null;
  costTargetProductTypeIds?: string[];
  editable?: boolean;
  bindings: SeasoningBindingView[];
}

export interface BomFamilyOutputCostingItem {
  recipeId: string;
  productTypeId: string;
  productName: string;
  outputRole: 'MAIN' | 'CO_PRODUCT' | 'BY_PRODUCT';
  costAllocationRatio: number;
  outputQuantity: number | null;
  outputUnit: string | null;
  byproductNrvUnitPrice: number | null;
}

export interface BomFamilyOutputCosting {
  bomFamilyId?: string | null;
  editable: boolean;
  outputs: BomFamilyOutputCostingItem[];
}

export interface UpdateBomFamilyOutputCostingRequest {
  outputs: Array<{
    recipeId: string;
    byproductNrvUnitPrice: number | null;
  }>;
}

export interface SeasoningMaterialUsage {
  bindingId?: number;
  workflowProcessNodeId?: string;
  workProcessId: string;
  processOrder: number;
  processName: string;
  basisQuantity?: number | null;
  basisUnit?: string | null;
  dosagePerKgG: number;
  subsequentPotRatio: number | null;
  countInSeasoning: boolean;
}

export interface SeasoningMaterialSummary {
  materialTypeId: string;
  materialName: string;
  materialCode?: string | null;
  unit?: string | null;
  priceSnapshot?: number | null;
  usages?: SeasoningMaterialUsage[];
  processUsages?: SeasoningMaterialUsage[];
}

export interface SeasoningAnomaly {
  code: string;
  message: string;
  bindingId?: number | null;
  materialTypeId?: string | null;
  workProcessId?: string | null;
}

export interface SeasoningWorkspace {
  recipeId: string;
  productTypeId: string;
  productName: string;
  status: BomRecipeStatus;
  editable: boolean;
  seasoningRevision: number;
  workflowRevisionId?: number | null;
  workflowId?: number | null;
  workflowOwnerProductTypeId?: string | null;
  workflowDefinitionVersion?: number | null;
  workflowRevisionHash?: string | null;
  workflowRevisionStatus?: string | null;
  workflowRevisionSavedAt?: string | null;
  workflowRootCount?: number | null;
  workflowTargetCount?: number | null;
  workflowProcessCount?: number | null;
  workflowTargetProductTypeId?: string | null;
  workflowUpgradeAvailable?: boolean;
  workflowUpgradeRevisionId?: number | null;
  workflowUpgradeDefinitionVersion?: number | null;
  bomFamilyId?: string | null;
  sharedRecipeId?: string | null;
  sharedRulesOwner?: boolean;
  outputRole?: 'MAIN' | 'CO_PRODUCT' | 'BY_PRODUCT' | null;
  costAllocationRatio?: number | null;
  processes: SeasoningProcessView[];
  materialSummaries: SeasoningMaterialSummary[];
  anomalies: SeasoningAnomaly[];
}

export interface SeasoningBindingMutation {
  workflowProcessNodeId?: string;
  materialTypeId: string;
  dosagePerKgG: number;
  subsequentPotRatio: number | null;
  countInSeasoning: boolean;
  remark?: string | null;
  substitutes?: BomSubstituteInput[];
  expectedRevision: number;
}

export interface SeasoningBindingMutationResponse {
  seasoningRevision: number;
  binding: SeasoningBindingView;
}
